AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for deploying a Lambda function from a Python file

Resources:
  APIForLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: MyLambda
      Handler: lambda.lambda_handler
      Role: arn:aws:iam::047989593255:role/service-role/tomasz-api-hello-world-role-53pra235
      Code:
#        ZipFile: !Sub |
#          fileb:///${LambdaCode}
        ZipFile: |
          def handler(event, context):
          pass
      Runtime: python3.12
